# CopyRight 2021 EveryOne

source ~/.vim/env/zsh/proxy.zsh

source ~/.vim/env/zsh/oh_my_zsh.zsh

source ~/.vim/env/zsh/alias.zsh

source ~/.fzf.zsh

source ~/.vim/env/zsh/fzf_custom.zsh

source ~/.local.zsh

source ~/.vim/env/zsh/navi.zsh

source ~/.vim/env/zsh/distcc.zsh
